# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orderbook_pb2 as orderbook__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in orderbook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderBookServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlaceOrder = channel.unary_unary(
                '/orderbook.OrderBookService/PlaceOrder',
                request_serializer=orderbook__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=orderbook__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/orderbook.OrderBookService/CancelOrder',
                request_serializer=orderbook__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=orderbook__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.GetOrderBook = channel.unary_unary(
                '/orderbook.OrderBookService/GetOrderBook',
                request_serializer=orderbook__pb2.GetOrderBookRequest.SerializeToString,
                response_deserializer=orderbook__pb2.OrderBookSnapshot.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/orderbook.OrderBookService/GetOrder',
                request_serializer=orderbook__pb2.GetOrderRequest.SerializeToString,
                response_deserializer=orderbook__pb2.OrderResponse.FromString,
                _registered_method=True)
        self.GetTradeHistory = channel.unary_unary(
                '/orderbook.OrderBookService/GetTradeHistory',
                request_serializer=orderbook__pb2.GetTradeHistoryRequest.SerializeToString,
                response_deserializer=orderbook__pb2.TradeHistoryResponse.FromString,
                _registered_method=True)


class OrderBookServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTradeHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=orderbook__pb2.PlaceOrderRequest.FromString,
                    response_serializer=orderbook__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=orderbook__pb2.CancelOrderRequest.FromString,
                    response_serializer=orderbook__pb2.CancelOrderResponse.SerializeToString,
            ),
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=orderbook__pb2.GetOrderBookRequest.FromString,
                    response_serializer=orderbook__pb2.OrderBookSnapshot.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=orderbook__pb2.GetOrderRequest.FromString,
                    response_serializer=orderbook__pb2.OrderResponse.SerializeToString,
            ),
            'GetTradeHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTradeHistory,
                    request_deserializer=orderbook__pb2.GetTradeHistoryRequest.FromString,
                    response_serializer=orderbook__pb2.TradeHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderbook.OrderBookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orderbook.OrderBookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderBookService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/PlaceOrder',
            orderbook__pb2.PlaceOrderRequest.SerializeToString,
            orderbook__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/CancelOrder',
            orderbook__pb2.CancelOrderRequest.SerializeToString,
            orderbook__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/GetOrderBook',
            orderbook__pb2.GetOrderBookRequest.SerializeToString,
            orderbook__pb2.OrderBookSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/GetOrder',
            orderbook__pb2.GetOrderRequest.SerializeToString,
            orderbook__pb2.OrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTradeHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/GetTradeHistory',
            orderbook__pb2.GetTradeHistoryRequest.SerializeToString,
            orderbook__pb2.TradeHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
